[workspace]
members = ["pyesim"]

[package]
name = "esim"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
csuperlu = { git = "https://github.com/lanamineh/csuperlu" }
regex = "1"
num = "0.4.0"