[workspace]
members = ["pyesim", "gui"]

[package]
name = "acdc"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
name = "libesim"

[dependencies]
csuperlu = { git = "https://github.com/lanamineh/csuperlu" }
regex = "1"
num = "0.4.0"